<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="1" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="130561" started-at="2018-08-07T08:22:28Z" finished-at="2018-08-07T08:24:39Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="130561" started-at="2018-08-07T08:22:28Z" finished-at="2018-08-07T08:24:39Z">
      <class name="screeshotpackage.Screenshot_Failed_Testcases">
        <test-method status="PASS" signature="setup()[pri:0, instance:screeshotpackage.Screenshot_Failed_Testcases@756e4d]" name="setup" is-config="true" duration-ms="39564" started-at="2018-08-07T13:52:28Z" finished-at="2018-08-07T13:53:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="login()[pri:0, instance:screeshotpackage.Screenshot_Failed_Testcases@756e4d]" name="login" duration-ms="90960" started-at="2018-08-07T13:53:08Z" finished-at="2018-08-07T13:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="FAIL" signature="teardown(org.testng.ITestResult)[pri:0, instance:screeshotpackage.Screenshot_Failed_Testcases@756e4d]" name="teardown" is-config="true" duration-ms="0" started-at="2018-08-07T13:54:39Z" finished-at="2018-08-07T13:54:39Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.TestRunner.afterRun(TestRunner.java:1014)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- screeshotpackage.Screenshot_Failed_Testcases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
